server.port: 8080

gateway:
  context-searcher.url: "http://localhost:8081"
  feedback-collector.url: "http://localhost:8082"

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:5173/'
            allowedMethods:
              - GET
              - POST
            allowedHeaders: '*'
