server.port: 8080
server.error.include-message: always

gateway:
  frontend:
    url: ${FRONTEND_URL}
  context-searcher:
    url: ${CONTEXT_SEARCHER_URL}
  feedback-collector:
    url: ${FEEDBACK_COLLECTOR_URL}
  admin-console:
    url: ${ADMIN_CONSOLE_URL}

  recaptcha:
    secret-key: ${RECAPTCHA_SECRET_KEY}
    verify-url: 'https://www.google.com/recaptcha/api/siteverify'

spring:
  security:
    user:
      name: ${SECURITY_USERNAME}
      password: ${SECURITY_PASSWORD}
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${gateway.frontend.url}
            allowedMethods:
              - GET
              - POST
            allowedHeaders: '*'
