gateway:
  context-searcher:
    url: 'http://localhost:8081'
  feedback-collector:
    url: 'http://localhost:8082'
  admin-console:
    url: 'http://localhost:5174'

  recaptcha:
    enabled: false

spring:
  data:
    redis:
      host: localhost
  security:
    user:
      name: 'admin'
      password: 'password'
